# Generated by Django 5.0.3 on 2024-03-11 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadership_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubleadership',
            options={'verbose_name_plural': 'Club Leadership'},
        ),
    ]
